title: Scott Draves
subtitle: Pioneering AI Artist & Engineering Leader
email: your-email@example.com
description: >-
  Scott Draves: Pioneering AI Artist & Engineering Leader
baseurl: ""
url: "https://draves.ai"


feature_icon_colour: "#69bbff"

collections:
  features:
    order:
      00_pioneering.md
      05_vj.md
      10_research.md
      15_leader.md
      20_academic.md
      25_prizes.md
      30_interview.md
      40_open.md
      50_innovative.md

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
